narodni adaptacni strategie in
faktaoklimatu/web pull request #552
Opened 2020-05-29 17:38 UTC by tomas-psorn

Přidal jsem doprovodný text a aktuální verzi infografiky k národní adaptační strategii. Prosím o kontrolu.

2020-05-30 06:27 UTC, kikinna commented
@tomas-psorn @ondraspribyla Počítám, že ta grafika je tam spíš ilustrativně a budeme se bavit, jestli a jak je třeba ji předělat?

2020-07-08 21:07 UTC, ondraspribyla commented
@tomas-psorn konečně jsem se dostal k podrobnému pročtení. Zabralo vám to hodně, je to ale dost dobrá a precizní práce... asi zatím textově nejnáročnější grafika

Myslím, že hlavní NEXT STEP je dokončit grafiku. 

Moje poznámky k textu: 
- namísto "finance" bych hledal lepší výraz - možná prostě "poznámka k finančním aspektům" - u různých opatření je poznámka různě hluboká, rozhodně nejde o analýzu nutných investic ale jen o orientační údaj... 
- příliš mnoho textu je tučně. Rád bych, abyste vybrali, co je skutečně důležité. 
- Přišlo by mi dobré rozlišit, které údaje pochází z dokumentu národní adaptační strategie a které jsou odjinud (například poznámky ke škodám v zemědělství??) a doplnit reference
- Celkově mi přišlo nejasné, co je shrnutí dokumentu NAS a co jsou ilustrační a výkladové texty... myslím, že by pomohlo se například odkazovat na strany dokumentu, například i formou odkazu na stránky jednotlivých kapitol. 
Jakože: DOPRAVA (v NAS str. 158-167)
 
@tomas-psorn  Co bys potřeboval k dokončení? Máš na to ještě energii, nebo to chceš hodit na někoho jiného?

2020-07-31 09:29 UTC, kikinna commented
@ondraspribyla 
Náhled grafiky (ubylo vazeb mezi projevy a oblastmi, ubylo textů v opatřeních, nový podnadpis).
Mrkneš prosím, jestli je to takhle ok? 

![narodni-adaptacni-strategie-01](https://user-images.githubusercontent.com/11555522/89021548-ffaa8180-d320-11ea-9f99-143ef60aed1e.png)

2020-07-31 11:22 UTC, ondraspribyla commented
Koukám na to a myslím že je to dobrý. Rád bych to dostal na web, aby Romana
s případně další mohli připomínkovat... Pak možná přijdeme na nějaká
vylepšení. Dotáhne někdo z vás Pull Request?

O.

Dne pá 31. 7. 2020 11:29 uživatel kikinna <notifications@github.com> napsal:

> @ondraspribyla <https://github.com/ondraspribyla>
> Náhled grafiky (ubylo vazeb mezi projevy a oblastmi, ubylo textů v
> opatřeních, nový podnadpis).
> Mrkneš prosím, jestli je to takhle ok?
>
> [image: narodni-adaptacni-strategie-01]
> <https://user-images.githubusercontent.com/11555522/89021548-ffaa8180-d320-11ea-9f99-143ef60aed1e.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/552#issuecomment-667029215>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EAD7M3LLL2NMXCA6RTR6KFJLANCNFSM4NOHGHEQ>
> .
>

2020-07-31 14:05 UTC, setcz commented
Ty jo, já to vidím teď poprvé a jsem z toho trochu zmaten. Je možné, že jsou dobré důvody proč grafika vypadá jak vypadá a proč je na ní tolik informací, tedy ignorujte mé komentáře, pokud máte lepší kontext. Berte to prosím jako testování někoho, kdo nemá žádný kontext a vidí jen tu infografiku.

Konkrétní podněty:

1) Nechápu tu levou část - co jsou ty věci "teplé zimy", "sucho", ...? To nemá žádný nadpis. 

2) Propojovacích čar je tam tolik, že to pro mě prostě dělá dojem chaosu, vůbec se mi to nespojuje do nějakého sdělení. 

3) Není mi jasné, co znamenají "dopady" - dopady na co? na tu danou oblast? Jakože třeba první řádek mám číst jako "dopady teplých zim a sucha na lesní hospodářství"?

(všechny tři předchozí věci) => pokud ano, nebylo by lepší k dané oblasti vypsat prostě do odrážek ty 1-3 věci zleva, které se s nima stane?

4) V pravé části je tolik textu, že aby asi člověk na to vzal lupu - to se nedá vložit do žádného článku na webu/ukázat v televizi/... A přijde mi to nestrukturované. => Nešlo by z toho aspoň udělat odrážkový seznam? 

5) Vlastně obecně - přijde mi to moc věcí na jednu infografiku. Nepomohlo by tomu rozdělit to třeba na 3-4 samostatné? (nebo radikálně, pro každou oblast mít samostatnou infografiku)

6) vizuální - proč mají ty jednotlivé oblasti vždy mezeru pod textem? Osobně bych asi text zarovnal vertikálně na střed té buňky

7)vizuální 2 - ten žlutej text Doprava (obzvlášť) a oranžovej Cestovní ruch už je hodně nekontrastní

2020-07-31 14:32 UTC, tomas-psorn commented
Díky za podněty.

1/ Tam jeeště můžeme přidat nadpis: Projevy změny klimatu

2 a 3/ Mělo by se to číst tímto způsobem:

Projev klimatické změny - na oblast - má následující dopady - které mohou omezit následující adaptační opatření

4 a 5/ Ta grafika je na text náročná, žádný jiný návrh zatím nefungoval dobře. Pokud by to bylo fakt nečitelné, můžeme to zkusit vymyslet jinak.

6/ Když to zarovnáme vertikálně na střed, tak to bude víc rozházené. Já mám pocit, že ta pravidelnost pomáhá čitelnosti.

7/ Zkusíme ty dvě barvy nahradit.

Během víkendu to možná nestihneme, kvůli změnám v grafice. Pokud by bylo v pořádku doladit grafiku a text podle připomínek, jak říká Ondráš, tak bych to do konce víkendu stihl.

2020-08-01 16:52 UTC, kikinna commented
Díky Sete za feedback.
Testování je obecně super, jsme za něj vděční.

Obecně je ta grafika jiná než ostatní, spíš přehledovka té zprávy. Nevím, jestli je to dobrý formát, ale bylo cílem udělat summary do jedné grafiky a tak jsme si řekli, že ji uděláme spíš čtecí a rozhodně není cílená do zpráv v televizi nebo článku.
Máš problém to přečíst, i když to vytiskneš na A4?

O barvách vím a nejsou dotažené, budu teprve řešit. Ad 6 Souhlasím s Tomem. Ad 3 - díky :) přeformulujeme.

2020-08-03 21:25 UTC, kikinna commented
Hh, udělali jsme s Tomem takovej experiment a potřebujeme zpětnou vazbu. Přidali jsme vysvětlující větu mezi nadpisy sloupečků. Možná to vůbec nefunguje a možná skvěle. :D 
@setcz @katkolouchova @mgrabovsky Co si o tom myslíte? (klidně jen stručně, klidně jen thumbs up a down). 
(Jinak bych asi trochu zesílila ten tenký řez. Ale pomáhá vám to se zorientovat v grafice?

![Adaptační strategie v1 0 test vety-02](https://user-images.githubusercontent.com/11555522/89228615-3cf06700-d5e0-11ea-85c5-636c03a7e13e.png)

2020-08-04 07:19 UTC, katkolouchova commented
@kikinna @tomas-psorn Kristi a Tome, mně to na první pohled moc nepomohlo. Spíš pro mě bylo obtížné přečíst celou tu větu naráz, jak se střídají slova verzálkami s malými písmeny. Možná by tomu mohlo pomoct, kdyby byla celá věta malými písmeny a klíčová slova by byla zvýrazněna jenom tučností.
Verze s tím, kde jsou vyznačené pouze projevy změny klimatu, oblasti, dopady a opatření bez dalšího textu pro mě funguje asi nejlíp. Na první pohled vidím, o co jde (protože má každá sekce jasně vymezený prostor) a nemusím vyvinou větší kognitivní námahu, abych se zorientovala, na rozdíl od prvního případu. Propojení se mi v hlavě poskládá samo :)

2020-08-04 07:40 UTC, setcz commented
Ty jo, to je fikaný! Je to trochu nekonvenční, ale vlastně se mi to líbí!

Nemělo by to být "projevy změn klimatu"? (jakože množné číslo)

---

Ještě koukám na ty propojovací čáry - je dané pořadí věcí v prvním sloupci a druhém sloupci? Přijde mi, že se dá snížit počet křížení - přikládám výsledek svého chvilkového hraní si, které sníží křížení z 21 na 10. možná to jde i líp (asi bude existovat i nějaký formální důkaz, kolik jich může být minimálně, jen já už všechno zapomněl:) ).  Tady je případně ten [slajd](https://docs.google.com/presentation/d/16gB54HcR8BNTpvKCFIZ18ABrRnJnDSVbLstDSloCu5w/edit#slide=id.p), kdybyste si s tím chtěli taky hrát a šoupat.

![pocet_krizeni](https://user-images.githubusercontent.com/10813593/89266561-591ef300-d636-11ea-95e5-e0b22b37238d.png)

2020-08-04 08:06 UTC, kikinna commented
@katkolouchova Kači, díky )) Já to tak nějak čekala :D Jakože něčím mi to přijde dobrý (chtělo se mi sdílet myšlenku), ale zároveň je to imho moc malý a ztracený, aby to zachránilo celou situaci.
Nicméně si nemyslím, že si ten význam každý člověk spojí jen kouknutím na ty nadpisy. 

@setcz Sete, to je fikaný! )) Líbí se mi tvůj přístup a rozhodně je to líp čitelný s méně překryvy. 
Nicméně nevím, jestli chceme měnit pořadí oblastí (jestli to odpovídá pořadí ve strategii a zároveň to odpovídá nějaké váze těch oblastí, Ondráš už kdysi navrhoval vyhodit posledních pár oblastí, protože jsou vlastně marginální), takže to nemůžu rozhodnout skrz obsah.
A taky to teď i pěkně sedí barevně (změnily by se třeba barvy zemědělství na modrou a vodního hospodářství na zelenou, zdraví na červenou), což si nejsem jistá, jestli nebude taky matoucí.

2020-08-05 11:50 UTC, setcz commented
Ha, umím to přešoupat ještě líp. Z 10 jsem to snížil na 6 křížení. Líp už to skoro jistě nejde. (Chápu, že můžou být důvody proč nechceme pořadí věcí měnit, ale kdyby přece jen, toto je možnost)

![krizeni_2](https://user-images.githubusercontent.com/10813593/89409489-729d6900-d722-11ea-88ef-837c541ed141.png)

2020-08-12 12:58 UTC, tomas-psorn commented
Další verze je hotová, prosím @ondraspribyla o review a návrh na druhého reviewera.

2020-08-25 10:16 UTC, ondraspribyla approved these changes

2020-08-25 17:52 UTC, mukrop requested changes
* Linkovana tabulka s datami nema nas format a nie je dotiahnuta (a nie je na spravnom mieste – treba ju prekopirovat na disk s finalnymi datasetmi). Pozrie sa na to @jankrcal?
* Dovolil som si zmenit vizualne strukturovanie textu. Prislo mi, ze sa v tom fakt velmi tazko orientuje. Mrknite na to – ak by sa vam to nezdalo, mozem to vratit (netrvam na tom, aj ked mne to takto pride lepsie).
* Upravil som technicke drobnosti (v medzicase sa zmenil format hlavicky).

2020-08-25 21:27 UTC, jankrcal commented
Na tabulku kouknu, snad zítra.

2020-09-19 16:11 UTC, jankrcal commented
Oj, to "zítra" se mi úplně nezdařilo, omlouvám se.

Přijde mi, že ten datový soubor nestojí za leštění, protože tam není nic navíc, smazal jsem ho z PR.
@tomas-psorn Pokud nesouhlasíš, Tome, tak ten datový soubor můžeme doplnit v dalším PR.

Martine, uděláš prosím merge nebo chceš ještě něco dodělat?

2020-09-24 07:28 UTC, mukrop commented
Hm, nie uplne suhlasim s @jankrcal. Pride mi, ze prinosnost nasich datasetov je aj v tom, ze sa odtial daju priamo kopirovat nami zostrucnene texty do prac novinarov napriklad. Presne ten isty pripad bolo [Srovnani mitigacnich opatreni](https://faktaoklimatu.cz/infografiky/mitigacni-opatreni-mmf).

Beriem to ale len ako cross-check s tebou, ak povies, ze to tam nechceme alebo ze to nema prioritu, mozes ten PR uz mergnut.

2020-09-24 07:28 UTC, mukrop approved these changes

2020-09-24 09:12 UTC, ondraspribyla commented
Řešili jsme to s Jeňou...
ano, úplně ideální by bylo mít u všech "objektů" (vizualizace,
explainer,...) nějakou
tabulku s daty. U grafiky typu "výtah z dokumentu" je to ale relativně malá
přidaná
hodnota (a pak stojí za to zadat to mladejm, ať se u těch výpisků učí)

Tedy s Jeňou jsme se dohodli, že u textových grafik (další bude "historie
výzkumu")
se pokusíme udělat dobře doprovodnej text (dobře odkazovanej)
a tabulku nebudeme přidávat.

Tedy Jeňo, můžeš to mergnout (dopaminy z merge nechávám tobě :-)

O.

On Thu, 24 Sep 2020 at 09:28, Martin Ukrop <notifications@github.com> wrote:

> Hm, nie uplne suhlasim s @jankrcal <https://github.com/jankrcal>. Pride
> mi, ze prinosnost nasich datasetov je aj v tom, ze sa odtial daju priamo
> kopirovat nami zostrucnene texty do prac novinarov napriklad. Presne ten
> isty pripad bolo Srovnani mitigacnich opatreni
> <https://faktaoklimatu.cz/infografiky/mitigacni-opatreni-mmf>.
>
> Beriem to ale len ako cross-check s tebou, ak povies, ze to tam nechceme
> alebo ze to nema prioritu, mozes ten PR uz mergnut.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/552#issuecomment-698168594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EBM6VC7SIPRJQFKVSLSHLYKZANCNFSM4NOHGHEQ>
> .
>

2020-09-24 09:46 UTC, tomas-psorn commented
Já souhlasím s tím, že ta tabulka nic moc nepřináší. Děkuju za kontrolu :)

2020-09-24 09:47 UTC, merged

2020-09-24 10:05 UTC, jankrcal commented
Vidím, že Tom si nenechal ujít dopaminy po velké práci :)
Díky všem!

Poznámka bokem: chci se Ondráši trochu ohradit proti komentáři o "mladejch", přijde mi to neadekvátní ageismus :) A navíc z toho cítím jistý disrespekt, který bych nechtěl v týmu cítit. Přál bych si přesnější formulace jako třeba "a pak stojí za to zadat někomu, kdo se u těch výpisků navíc bude učit o tématu".

2020-09-24 10:24 UTC, ondraspribyla commented
Ad "Mladejch" - nemyslel jsem to jako vymezování věkem, ale integrací do
projektu, a nemám v tom téma respektu, ale pragmatické alokace zdrojů.
Nechci takovou práci zadávat lidem, kteří mohou přinést větší hodnotu než
vyplňovat tabulku.
Na druhou stranu už nechci zadávat "velkou práci" lidem, kteří s náma
začínají... Mnoho takových odpadlo bez toho, aby cokoliv užitečného
dokončili.
Prostě potřebujeme dostatečně malé a jednoduché tasky, které můžeme zadávat
lidem, kteří se chtějí přidat - a tím si lidi testovat,
abych nelil svou energii někam zbytečně - toho jsem si při hackatonech užil
hodně.

O.

On Thu, 24 Sep 2020 at 12:06, jankrcal <notifications@github.com> wrote:

> Vidím, že Tom si nenechal ujít dopaminy po velké práci :)
> Díky všem!
>
> Poznámka bokem: chci se Ondráši trochu ohradit proti komentáři o
> "mladejch", přijde mi to neadekvátní ageismus :) A navíc z toho cítím jistý
> disrespekt, který bych nechtěl v týmu cítit. Přál bych si přesnější
> formulace jako třeba "a pak stojí za to zadat někomu, kdo se u těch výpisků
> navíc bude učit o tématu".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/552#issuecomment-698248485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EG6VGXXRFW7OZR44ATSHMKYRANCNFSM4NOHGHEQ>
> .
>

2020-09-24 10:53 UTC, mukrop commented
Ano, tomu rozumime a suhlasim (a asi aj Jena). Ale suhlasim s nim, ze nechcem sklznut k (napriklad instruktorskej) terminologii typu stenata vs. stari psi. Vnimam to len ako prosbu na presnejsie vyjadrovanie, ktore sa neda interpretovat ako despekt :-).
(Takze suhlas, urobia nam to nejaki novi clenovia timu ako uvodny task, zakladam na to issue...)