Upraven design titulní strany, další drobná vylepšení
faktaoklimatu/web pull request #635
Opened 2020-08-18 14:09 UTC by mukrop

* Uvodna strana ma novu sekciu "nove", kde sa zobrazuju najnovsie infografiky a studie. Logika titulky je nasledovna: V prvej sekcii sa zobrazuje 6 najnovsich veci, ostatne sekcie su tematicke a zobrazuje sa tam max 6 veci, ktore sme my vybrali v poradi, ktore sme my urcili (aby to bol "dobry reprezentativny vyber").
* Jednotlive tematicke sekcie zobrazuju najviac 6 objektov, ak ich je viac, linkuju na stranku s prehladom temy.
* Jemne upraveny pruh so suvisiacimi infograikami na spodu stranok infografik: zobrazuju sa aj sekcie, rovnaky pruh je aj pod studiami, stylovo to zodpoveda uvodnej stranke (takze je to vacsie, su tam len 3 veci a ma aj stitky).

Co je treba
* [ ] Prejst/upravit nazov a intro text prvej sekcie s novymi vecami na titulnej strane (trochu som si nevedel s copywritingom poradit, mohlo by to byt asi aj lepsie).
* [ ] Zamysliet sa, ake objekty chceme zobrazovat na titulke k klime, emisiam a energetike (niektore su teraz uz skryte, kedze ich je nad 6 a mozno tam chcete zobrazovat aj nejaku studiu, alebo naopak nie).

2020-08-18 19:57 UTC, ondraspribyla commented
Vidím to rozhodně jako zlepšení (jsem zvyklý na dřívější podobu stránek, ale můj zvyk není relevantní pro uživatele)
zobrazovat prvních šest ze sekce je super, odkaz na další v "šestém" políčku je velmi intuitivní. 
Sekce "nové" je asi taky fajn... tady mi to nesedí na můj zvyk, ale myslím, že pro běžné uživatele to bude lepší. 
Mám radost ze sjednodušení horní lišty... je v ní teď potenciálně prostor na Explainery, materiály do výuky, Pro Média nebo jiné "služby" které bychom výlhedově mohli chtít nabízet. 

Jsem rozhodně pro, Approoved! Díky moc!

2020-08-18 20:17 UTC, mukrop commented
@ondraspribyla vyber prominentne zobrazovanych 6 studii a infografik ti vyhovuje tak, ako je  teraz? (Ide o to, kde prioritiovat/deprioritizovat zobrazenie studie v tych vybranych siestich).
Idealne pockam este na jedno technickejsie review (Matej, Jena, ...)

2020-08-18 20:25 UTC, ondraspribyla commented
Nad těmi výběry by se dalo strávit více času diskusema... je to dostatečně
dobrý, abych to teď neřešil a klidně to svěřím někomu jinému v týmu :-) ať
mají mladíci co dělat, aspoň si budou muset nastudovat co se tam zobrazuje
:-)

On Tue, 18 Aug 2020 at 22:17, Martin Ukrop <notifications@github.com> wrote:

> @ondraspribyla <https://github.com/ondraspribyla> vyber prominentne
> zobrazovanych 6 studii a infografik ti vyhovuje tak, ako je teraz? (Ide o
> to, kde prioritiovat/deprioritizovat zobrazenie studie v tych vybranych
> siestich).
> Idealne pockam este na jedno technickejsie review (Matej, Jena, ...)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/635#issuecomment-675691055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EAYNGBVAFP235A5VOLSBLOVPANCNFSM4QDRAVHA>
> .
>

2020-08-23 19:33 UTC, jankrcal commented on _datasety/emise-cr.md
> +published:  2020-04-19
Můžou tady syntakticky být komentáře? Přišlo by mi fajn všechna tato data 04-19 označit jako 
# Toto není skutečné datum zveřejnění, pouze vyjadřuje "starší než nás zajímá pro titulku".

2020-08-23 20:12 UTC, jankrcal requested changes
Zatím jsem do detailu neřešil titulní grafiky / studie, jen označuju pár věcí, co mě tam rušilo.

Jinak je to veskrze technické review.

2020-08-23 20:12 UTC, jankrcal commented on _layouts/study.html
> +    {% assign objects = site.infografiky | concat: site.studie | where_exp: "item", "item.tags contains page.tags-topics[0]"
Krome toho nejsem stastny z takove deterministicke volby souvisejicich objektu, protoze u velkeho tematu tam u kazde grafiky / studie budou ty prvni 4 objekty podle vahy.

Je v tom vedomy zamer, ze jsi smazal "| sample ..."? Pokud ano, nejake lepsi reseni bych nicmene nechal na jiny PR, nespecha to za me.

2020-08-23 20:12 UTC, jankrcal commented on _stranky/index.md
> +{% include preview-blocks.html blocks=objects link="news" limit=6 %}
Mám problém s tím, že novinky mají úplně stejný formát jako každá další sekce. Podle mě to brání pochopení struktury webu. Zkoušel jsem nějakou úplně jinou barvu pozadí, nefunguje. Nedalo by se tomu pruhu novinek ponechat bílé pozadí (stejně jako horní část webu) a barevné-bílé začít střídat až od první tematické sekce?

2020-08-24 20:30 UTC, mukrop commented on _layouts/study.html
> +    {% assign objects = site.infografiky | concat: site.studie | where_exp: "item", "item.tags contains page.tags-topics[0]"
Davat to ako include je podla mna v tomto momente premature optimization, zbytocna komplikacia. Ked to bude aspon 3x, zvazim (a je dost pravdepodobne, ze sa to casom stane).

Sample som vratil spat, to je dobry postreh.

2020-08-24 20:31 UTC, mukrop commented on _stranky/index.md
> +# Nejnovější grafiky, studie a datasety
Ack.

2020-08-24 20:31 UTC, mukrop commented on _stranky/index.md
> +Zajímá vás, co máme nové? V této sekci vždy najdete výběr těch nejnovějších infografik, výtahů studií a datasetů z naší dílny. Úplný seznam novinek a aktualit najdete i v [přehledu na samostatné strá
Ack.

2020-08-24 20:31 UTC, mukrop commented on _stranky/index.md
> -Zde pro vás vybíráme nejdůležitější studie, články a analýzy týkající se změn klimatu – vždy uvádíme, proč je studie důležitá, jaké jsou její hlavní závěry a další komentáře a poznámky.
Pridal som.

2020-08-24 20:31 UTC, mukrop commented on _stranky/index.md
> -Najít data vědeckých či statistických institucí a zorientovat se v nich, to je velký kus naší práce. Její výsledek dáváme k dispozici v této sekci s přehledem našich datasetů. V sekci _Naše datasety_
Pridal som.

2020-08-24 20:32 UTC, mukrop commented on _studie/2018_energetika-cr-bez-uhli.md
>  tags-topics: [ opatreni, energetika, emise ]
Logika "mazat tagy kvoli titulke" mi nepride dobra. Prerobil som vahy, aby sa na titulke zobrazovali vsetky veci najviac raz (a aby sa v energetike a emisiach zobrazovali veci, ktore mi pridu relevantnejsie).

2020-08-24 20:32 UTC, mukrop commented on _studie/2020_globalni-zprava-o-elektrine.md
>  tags-topics: [ energetika, emise ]
Vid komentar vyssie.

2020-08-24 20:33 UTC, mukrop commented on assets/_scss/index.scss
> +    background-image: radial-gradient(white 30%, rgba(255,255,255,0.8) 60%, transparent 100%);
Prekryl som grafiku farbou, ale v ramci konzistentneho stylu som zachoval gradient.

2020-08-24 20:33 UTC, mukrop commented on _stranky/index.md
> +{% include preview-blocks.html blocks=objects link="news" limit=6 %}
Tiez som nad tym rozmyslal, ale povedal som si, ze to je asi detail. Ale ked si to vytiahol aj ty, skusil som dat modre pozadie. Co ty na to? Mne sa to celkom pozdava. Sice to trochu taha pozornost k tej sekcii, ale kedze su to novinky, vlastne mi to asi pride dobre.

2020-08-25 05:16 UTC, jankrcal commented on _stranky/index.md
> +{% include preview-blocks.html blocks=objects link="news" limit=6 %}
Přijde mi to supr. Nevím, jak moc je ta barva z naší palety, ale vypadá to za mě dobře a navíc se to dá doladit časem.

2020-08-25 05:16 UTC, jankrcal commented on assets/_scss/index.scss
> +    background-image: radial-gradient(white 30%, rgba(255,255,255,0.8) 60%, transparent 100%);
Ideální

2020-08-25 05:20 UTC, jankrcal commented on _studie/2018_energetika-cr-bez-uhli.md
>  tags-topics: [ opatreni, energetika, emise ]
Poladění vah je za mě dobré. 

Pořád trvám na tom, že mít Energynautics jako jediné v sekci "opatreni" je asymetrické. Pokud to chceš zachovat, tak navrhuju doplnit do sekce opatreni také tyto dvě věci (protože se prostě dotýkají opatření):
 - studie/2020_transformace-energetiky-do-2050
 - infografiky/uhelny-phaseout-eu

2020-08-25 05:22 UTC, jankrcal commented on _layouts/study.html
> +    {% assign objects = site.infografiky | concat: site.studie | where_exp: "item", "item.tags contains page.tags-topics[0]"
Ack

2020-08-25 05:26 UTC, jankrcal commented on _layouts/tag.html
> +            <p class="lead">Naše infografiky, týkající se tématu. Na stránce grafiky vždy naleznete zdroj dat i podrobnější informace.</p>
Ještě detail, smazal bych čárku v první větě, je to [přívlastek těsný](https://www.pravopisne.cz/2018/07/pravidla-privlastek/#b)-privlastek-tesny)

2020-08-25 06:15 UTC, jankrcal requested changes
Díky za úpravy!

Pořád jsem i na drobné úpravy vah použil komentáře, protože mi to přijde důležité diskutovat a argumentovat, než abych tam něco udělal nesrozumitelně vlastním commitem.

2020-08-25 06:15 UTC, jankrcal commented on _infografiky/emise/emise-svet.md
>  weight:     94
Dal bych nižší váhu: přijde mi toto důležitější na titulce, než obě dvě složité emise-na-osobu/hdp.

2020-08-25 06:15 UTC, jankrcal commented on _infografiky/energetika/elektrina-na-osobu-eu.md
> +weight:     110
Prohodil bych váhu s IRENA. Navštěvovaná grafika. Ze studií stačí na titulce EMBER a IRENA bude pod tlačítkem.

2020-08-25 17:07 UTC, mukrop commented on _studie/2018_energetika-cr-bez-uhli.md
>  tags-topics: [ opatreni, energetika, emise ]
To je dobra pripomienka, temy som im pridal.

2020-08-25 17:08 UTC, mukrop commented on _stranky/index.md
> +{% include preview-blocks.html blocks=objects link="news" limit=6 %}
Je zhruba z nasej palety. Zobral som svetlu modu, ktoru pouzivame, dal jej transparecy a potom to prepisal na absolutnu farbu (kvoli tomu pouzitiu v gradiente).

2020-08-25 17:09 UTC, mukrop commented on _layouts/tag.html
> +            <p class="lead">Naše infografiky, týkající se tématu. Na stránce grafiky vždy naleznete zdroj dat i podrobnější informace.</p>
To je pravda, odstranil som.

2020-08-25 17:14 UTC, mukrop commented on _studie/2019_klimaticke-podminky-cr-1.md
>  weight:     140
OK.

2020-08-25 17:15 UTC, mukrop commented on _infografiky/teploty/teplota-22000-let.md
>  weight:     100
OK.

2020-08-25 17:17 UTC, mukrop commented on _infografiky/emise/emise-vybrane-staty.md
>  weight:     96
OK.

2020-08-25 17:17 UTC, mukrop commented on _infografiky/emise/emise-svet.md
>  weight:     94
OK.

2020-08-25 17:22 UTC, mukrop commented on _infografiky/energetika/elektrina-na-osobu-eu.md
> +weight:     110
OK.

2020-08-25 17:24 UTC, mukrop commented
Upravil som myslim vsetko. Mrkni na to. Ak ti to pride OK, daj approve a rovno rebase & merge.

2020-08-25 20:54 UTC, jankrcal approved these changes
Supr, dík!

2020-08-25 20:59 UTC, mukrop commented
Hm, co chalani (@ondraspribyla a @protivinsky) robite? Pridali ste do tejto vetvy commity, ktore sem vobec nepatria. Mozem to precistit a mergnut bez toho?

2020-08-25 21:01 UTC, mukrop commented
Pardon, ten komentar nemal byt pre @ondraspribyla a @protivinsky, teraz vidim, ze to robil @jankrcal v snahe vyriesit konflikty. Mozte to teda ignorovat, Jena to predpokladam doriesi.

2020-08-25 21:05 UTC, merged

2020-08-25 21:07 UTC, jankrcal commented
@mukrop Jo jo, omlouvám se. Snad už vyřešeno.