Schema klimatu - nová grafika
faktaoklimatu/web pull request #637
Opened 2020-08-20 16:18 UTC by ondraspribyla

Doplněna grafika + text (v podstatě kopie textu z připravované brožury)
Prosím @protivinsky nebo @crysman o review textu... 

Known issues: tato grafika v podstatě nemá zdroj, jen shrnuje co se děje a může sloužit jako základní rozcestník...
tímpádem nemáme "naše data" ani "zdrojová data". Nechal bych to tak, ale třeba vás napadne jiné řešení. 

O.

2020-08-20 17:19 UTC, mgrabovsky commented
Typografické a pravopisné drobnosti v grafice:
* Podle SSJČ je „schematická“ (s krátkým _e_) jediná přípustná forma.
* V podnadpisu: má být „nár**ů**st“.
* Předposlední bod v pravém sloupci: má být „koncentr**a**cí“.
* Poslední bod tamtéž: na konci přebývá písmenko _i_.
* Subskript v „CO₂“ v nejlevější bramboře je jiný než u „O₂“ dole v pravém sloupci.

Zdá se mi redundantní psát „Tání pevninských ledovců Grónska, Antarktidy a _horských ledovců_“, když máme zvlášť bramboru „Tání horských ledovců“.

Další known issue je problém s ořezem na webu (viz #627).

2020-08-23 21:14 UTC, crysman commented
blokuje mě https://github.com/faktaoklimatu/web/issues/638

2020-08-25 10:11 UTC, ondraspribyla commented
@mukrop doplnil jsem ještě pár řádků textu o zjednodušeních. Vzhledem k tomu, že texty budeme hromadně vylapšovat na podzim bych to proteď pokládal za finální verzi a poprosil o MERGE. Později texty doplníme nebo upravíme tak, aby měly lepší flow a obsahovaly podstatné věci.

2020-08-25 18:00 UTC, mukrop requested changes
* Ake ma tato grafika zdroje? Aktualne neuvadzame ziadne ani v grafike ani v dokumente. Ak naozaj ziadne uvadzat nechceme (naozaj?), tak je potrebne upravit sablonu stranky, ze ked zdroje nie su uvedene, tak za nezobrazuje sekcia s tlacitkom vpravo. (Mozem to urobit, zle potrebujem potvrdit, ze to naozaj chceme tak.)
* V grafike je aktualne orezany nadpis "Vybrane dopady na ekosystemy a spolocnost" (je tam z toho len "spolocnost"). Co s tym? Zda sa mi to nevhodne publikovat takto, ale ak poviete, ze ano, tak to zvladnem  :-).

2020-08-25 18:08 UTC, ondraspribyla commented
Ohledně Zdrojů: myslím, že v tomto případě bude asi nejlepší skutečně žádné
neuvádět. Grafiku jsem podrobně diskutoval s Michalem Žákem a máme jeho
approval. Jde prostě o jeden ze způsobů (nikoliv jediný) jak uspořádat
informace o klimatické změně do nějakého schématu... a každé schéma je
špatně, některá schémata jsou užitečná... :-) Zdroje a odkazy se potom
snažím uvádět v textu takže mohla by být varianta napsat, že zdroje jsou
uvedeny v textu. Anebo nechat původní zdroje prázdné - to mi přijde
jednodušší a bude se to asi opakovat u několika dalších grafik, které mají
takto přehledový charakter. (např u časové osy výzkumu skleníkového
efektu). Co si o tom myslíš?

Ad ořez nadpisu: víme o tom, s Kristi jsme to řešili a lepší to asi
neuděláme.

On Tue, 25 Aug 2020 at 20:00, Martin Ukrop <notifications@github.com> wrote:

> *@mukrop* requested changes on this pull request.
>
>    - Ake ma tato grafika zdroje? Aktualne neuvadzame ziadne ani v grafike
>    ani v dokumente. Ak naozaj ziadne uvadzat nechceme (naozaj?), tak je
>    potrebne upravit sablonu stranky, ze ked zdroje nie su uvedene, tak za
>    nezobrazuje sekcia s tlacitkom vpravo. (Mozem to urobit, zle potrebujem
>    potvrdit, ze to naozaj chceme tak.)
>    - V grafike je aktualne orezany nadpis "Vybrane dopady na ekosystemy a
>    spolocnost" (je tam z toho len "spolocnost"). Co s tym? Zda sa mi to
>    nevhodne publikovat takto, ale ak poviete, ze ano, tak to zvladnem :-).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/637#pullrequestreview-474725597>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EEDZJ4AIP56M4RN5LTSCP33HANCNFSM4QGKLXTA>
> .
>

2020-08-25 18:28 UTC, mukrop commented
Hm, tak grafiku asi zvladneme aj takto.
OK, tak teda bez zdrojov, prerobim to, aby sa ta sekcia nezobrazovala.

>

2020-08-25 18:39 UTC, mukrop approved these changes

2020-08-25 18:39 UTC, merged