Emise ČR: aktualizace na rok 2018
faktaoklimatu/web pull request #642
Opened 2020-09-06 13:38 UTC by jankrcal

Tato změna aktualizuje infografiky a texty k emisím ČR z roku 2016 na rok 2018.

2020-09-06 13:40 UTC, jankrcal commented
Prosím @ondraspribyla o obsahové review. Technicky tam nejsou žádné změny, tak bych technické review přeskočil.

Ta konkrétní čísla v textech, to byla docela fuška, nevím, jestli máš energii to procházet a znovu kontrolovat...

2020-09-07 08:40 UTC, ondraspribyla requested changes
U datasetu, který je správně updatovaný na rok 2018, se stále zobrazuje náhled, který je za rok 2016. Je to trochu matoucí... Vzhledem k tomu, že se Jeňa připravuje na vystoupení v senátu a finišuje věci k systémová vs individuální: mohli by tuto technickou úpravu udělat @mgrabovsky  nebo @mukrop  a pak mergenout? 
V případě, že by měl @mgrabovsky čas, přišlo by mi super, kdyby mohl i zkontrolovat data v datasetu a v grafice. Odlaďovali jsme pár chyb, tak doufám, že tam další nezbyly... Díky moc!!

O.

2020-09-07 09:14 UTC, jankrcal commented
Aha aha, technicky by mělo stačit spustit v dané branch:

utils/download-dataset-preview.sh _datasety/emise-cr.md assets/datasets/emise-cr.png

Nějak mi to nefunguje, tak bych ocenil, kdyby to udělal někdo jiný. Pro @mukrop je to asi drobnost? (Až na to, že spolufacilituješ výjezd...)

2020-09-07 16:06 UTC, mukrop approved these changes
Vyzera OK.

2020-09-07 16:07 UTC, mukrop commented
Robim merge kvoli zajtrajsiemu okruhlemu stolu, inak kontrola dat od @mgrabovsky by bola dobra aj dodatocne.

2020-09-07 16:07 UTC, merged

2020-09-08 09:14 UTC, mgrabovsky commented
Data rád zkontroluju, nejdřív ale až ke konci příštího týdne.

2020-09-08 11:40 UTC, jankrcal commented
To úplně stačí, díky!

Dne út 8. 9. 2020 11:15 uživatel Matěj G. <notifications@github.com> napsal:

> Data rád zkontroluju, nejdřív ale až ke konci příštího týdne.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/642#issuecomment-688736794>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDOSZIMH3VLYXOSFIZ23TSEXY2HANCNFSM4Q4NLPQA>
> .
>