Infografika vývoje emisí ČR od 1990
faktaoklimatu/web pull request #653
Opened 2020-10-01 20:07 UTC by mgrabovsky

Nahodil jsem doprovodný text k infografice historického vývoje emisí ČR. Větší část je převzatá z [detailního donutu](https://faktaoklimatu.cz/infografiky/emise-cr-detail), část z diskuze pod #601.

Prosím @ondraspribyla, @SklenarOldrich a další povolanější o kontrolu a případné korekce a doplnění. (Třeba mě teď nenapadá, jak napsat emise ČR v roce 1990, když ČR ještě neexistovala.)

Mimo text zbývá ještě rozhodnout o váze infografiky a doplnit dataset.

2020-10-04 10:05 UTC, jankrcal requested changes

2020-10-04 10:05 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +* __Odpadové hospodářství:__ Emise z odpadového hospodářství od devadesátých let setrvale rostou. Do roku 2018 stouply o 83 % na 5,7 mil. tun CO<sub>2</sub>eq ročně. Produkují je především skládky od
pro větší čitelnost: ... biometanu, který se namísto zemního plynu může využít například v dopravě.

2020-10-04 10:05 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +* __Zemědělství:__ Emise ze zemědělského sektoru klesly od roku 1990 o 45 % na 8,61 mil. tun CO<sub>2</sub>eq ročně. Emise pocházejí především z chovu hospodářských zvířat a z obdělávání půdy a s tím
Co vedlo ke snížení? Snížení stavu dobytka? Nebo všechny ty zdroje dohromady?

Současně bych volil neutrálnější výrazy: K omezení emisí ... by *vedlo* ...

2020-10-04 10:13 UTC, SklenarOldrich commented on _infografiky/emise/emise-cr-vyvoj.md
> +* __Doprava:__ Emise z dopravy vzrostly oproti roku 1990 o 69 % na 20,3 mil. tun CO<sub>2</sub>eq ročně. V detailním grafu napravo je po roce 2008 patrný dočasný pokles emisí v důsledku globální fina
lze sledovat (x patrný)

postupným přechodem alternativní pohon (např. na elektřinu, biometan nebo CNG), dalším zvýšením podílu hromadné (vlakové a autobusové) dopravy, snížením dopravy (tj. pohybu dopravních prostředků) při zachování přepravního výkonu (tj. počtu přepravených osob) pomocí vyšší obsazenosti vozidel (většina osobních automobilů je certifikována pro 5 pasažérů, zatímco jejich průměrná obsazenost se pohybuje kolem 2, ve velkých městech potom i 1,3 osoby na vozidlo) případně obecně snížením nutnosti přepravy (např. pomocí práce na dálku).

2020-10-04 10:32 UTC, SklenarOldrich commented
Určitý přehled o importu/exportu emisí lze získat např. z tohoto zdroje.

https://www.carbonbrief.org/mapped-worlds-largest-co2-importers-exporters

2020-10-07 18:33 UTC, mgrabovsky commented
Na základě naší diskuse jsem aktualizoval text, doplnil a (snad) vyjasnil pár detailů a přidal záznam do aktualit.

Prosím @jankrcal a případně @SklenarOldrich o kontrolu.

2020-10-07 18:50 UTC, SklenarOldrich approved these changes

2020-10-07 18:51 UTC, SklenarOldrich approved these changes
Za mě OK - může jít na web. Díky!

2020-10-07 19:43 UTC, jankrcal requested changes
Za mě textově skvělý, děkuju moc!

Teď už jen technický věci...

2020-10-07 19:43 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +dataset:       "emise-cr"
Máme nějaký +- pročištěný Google Sheet?

Já v rychlosti vidím jen toto, což ještě není v požadované kvalitě:
https://docs.google.com/spreadsheets/d/1LI2sArKOHn_VYzwkIygBsEB9eTZiYzGknyvEpvNmNr4/edit#gid=1517701319

Pokud ne, máš kapacitu to trochu pročistit v našem stylu?
(tohle by asi taky bylo dobrý na jupyter, ale ještě na to myslím nejsme ready)

2020-10-07 19:43 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +  K největšímu poklesu, o polovinu, došlo v první polovině devadesátých let zejména v důsledku ukončení energeticky náročných průmyslových provozů. Konkrétně emise ze spalování v těžkém průmyslu (výr
Děkuju za podrobnou rešerši, to je skvělý! Vrtá mi hlavou, jak je možný takový nesoulad v těchto dvou kategoriích pro výrobu oceli a železa, máš nějaké vysvětlení, @SklenarOldrich?

Dokážu si představit, že by se zvýšila efektivita provozu, ale stáhnout spalování uhlí na jednotku oceli/železa cca na pětinu mi přijde "too good to be true". Druhá možnost je, že se změnila struktura výrobků a tak je potřeba míň tavit, ale přitom se z těch procesů uvolňuje stejně.

Nepotřebuju zde nic měnit, jen jsem zvědavý...

2020-10-07 19:43 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +weight:        55
Klidně bych to dal momentálně na 5. pozici v kategorii "emise", tedy za srovnání 7 států EU.

2020-10-07 19:57 UTC, mgrabovsky commented on _infografiky/emise/emise-cr-vyvoj.md
> +weight:        55
OK.

2020-10-07 19:58 UTC, mgrabovsky commented on _infografiky/emise/emise-cr-vyvoj.md
> +dataset:       "emise-cr"
Hezkou tabulku nemáme, všechno jsem dělal v Rku. Dataset bych mohl připravit, ale váhám, jestli to bude efektivní a jestli nebude lepší ho odložit, až budeme mít nachystaný proces pro Jupyter.

2020-10-07 20:04 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +dataset:       "emise-cr"
Souhlasím, leštit tabulku je nefektivní. Přijde mi nefér u takové grafiky ale nemít žádný zdroj dat.

Pokud jsi ochotný se zavázat, že prioritně vyrobíš jupyter notebook, až na to bude proces, tak bych navrhoval prostě toto: strávit leštěním Google tabulky max 10-15 minut, bude to odbytý a nebude zdaleka splňovat naše standardy, ale bude to tak jen na chvilku. Dává Ti to tak smysl? Pokud by se Ti vyloženě nechtělo leštit, asi to můžu udělat, ale spíš až v pátek.

@protivinsky Jaký máš časový odhad na první zveřejněné notebooky v jupyteru? Je to v řádu nízkých jednotek týdnů nebo spíše počítat déle?

2020-10-07 20:22 UTC, SklenarOldrich commented on _infografiky/emise/emise-cr-vyvoj.md
> +  K největšímu poklesu, o polovinu, došlo v první polovině devadesátých let zejména v důsledku ukončení energeticky náročných průmyslových provozů. Konkrétně emise ze spalování v těžkém průmyslu (výr
@jankrcal Ad snížení emisí při spalování v těžkém průmyslu - zatím jsem to podrobněji nezkoumal, takže nevím. Nicméně to může být opravdu jinou strukturou finálních produktů. Napadá mě ještě možná recyklace vysokopecního plynu, který může nahrazovat část původně spotřebovávaných primárních paliv, případně dokonalejší využití odpadního tepla se stejným efektem. 

Přidávám si do témat, kterým se budu v budoucnu věnovat...

2020-10-07 20:37 UTC, mgrabovsky commented on _infografiky/emise/emise-cr-vyvoj.md
> +dataset:       "emise-cr"
OK, to beru. Dostanu se k tomu ale zase až zítra večer.

2020-10-08 05:57 UTC, jankrcal commented on _infografiky/emise/emise-cr-vyvoj.md
> +dataset:       "emise-cr"
Supr, dík!

2020-10-08 18:07 UTC, mgrabovsky commented
@jankrcal V rychlosti jsem zpracoval tabulku a přidal odkaz. Prosím o kontrolu.

2020-10-08 18:21 UTC, mukrop approved these changes

2020-10-08 18:23 UTC, mukrop commented
@jankrcal prosim o potvrdenie, ze tvoje ziadane zmeny su zapracovane.
Ak ano, mozes urobit merge.

2020-10-08 19:12 UTC, jankrcal commented
Ano, za mě je to good enough, děkuju mnohokrát!

2020-10-08 19:12 UTC, jankrcal approved these changes

2020-10-08 19:12 UTC, merged

2020-10-08 19:25 UTC, jankrcal commented
Matěji, můžeš ještě prosím ten dataset [1] přesunout do složky datasety finální [2]? Mám podezření, že to je na Tvém disku :)

[1] https://docs.google.com/spreadsheets/d/1CfPYmK_buWl4pYH025dbCo3mj2bCzZ2udxRbUujdrm0/edit#gid=668390753
[2] https://drive.google.com/drive/folders/1L3Kr9Gh6lclkL8WWv9YdfAfByyitxesg

2020-10-08 19:52 UTC, mukrop commented
Jeno, len upozornujem, ze datasety sme chceli premigrovat sa samostatny
zdielany disk, ktory na to uz je (ale je privilegovany, presunut tam by si
to musel ked tak ty).

2020-10-08 19:59 UTC, jankrcal commented
Martine, vím o tom, však to tam v druhém kroku plánuju přesunout :)

čt 8. 10. 2020 v 21:52 odesílatel Martin Ukrop <notifications@github.com>
napsal:

> Jeno, len upozornujem, ze datasety sme chceli premigrovat sa samostatny
> zdielany disk, ktory na to uz je (ale je privilegovany, presunut tam by si
> to musel ked tak ty).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/653#issuecomment-705788013>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDOS2ZDZDJBIXCCVPZ6XTSJYJ75ANCNFSM4SA4ESSA>
> .
>

2020-10-08 20:20 UTC, mgrabovsky commented
Přesunuto ✔