Přidána licence
faktaoklimatu/web pull request #654
Opened 2020-10-01 20:13 UTC by mukrop

2020-10-02 08:52 UTC, mgrabovsky commented
Jistější by asi bylo explicitně označit, že MIT se vztahuje na kód a infrastrukturu a že pro grafiky a texty platí CC-BY.

2020-10-02 09:23 UTC, mukrop commented
Preto to tu visi ako PR, chcel som to s niekym prebrat (asi s tebou) a doplnit info do Readme (myslis, ze aj do suboru s licenciou?).

2020-10-03 09:13 UTC, mgrabovsky commented
Případně jako modernější alternativu k MIT navrhuju [Blue Oak](https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html).

2020-12-05 13:08 UTC, mgrabovsky requested changes
Vypadá dobře. Ještě by mi přišlo fajn mít krátké shrnutí nebo odkaz na ten soubor licenci dole v readme.

2020-12-05 13:08 UTC, mgrabovsky commented on LICENSE.md
> +Specifické informace o licenci najdete na našich stránkách. Není-li řečeno jinak, je licence následovná"
```suggestion
Specifické informace o licenci najdete na našich stránkách. Není-li řečeno jinak, je licence následovná:
```

2020-12-05 13:52 UTC, mukrop commented
Upravil som (a pri tej prilezitosti lintoval Readme). Prosim o druhe review.

2020-12-05 14:03 UTC, mgrabovsky approved these changes
Looks good.

2020-12-05 14:03 UTC, merged