Emise SR podle sektorů detailně (verze 2)
faktaoklimatu/web pull request #666
Opened 2020-10-08 21:22 UTC by jankrcal

2020-10-08 21:26 UTC, jankrcal commented
Martine, mohl bys prosím projít doprovodný text? (detailní čísla nekontroluj, to je nemožný úkol, zajímá mě, jestli Ti to jako Slovákovi dává smysl)

2020-10-08 21:41 UTC, jankrcal commented
Katko, mohla bys prosím v titulcích grafiky nahradit SR za Slovensko? (a nahrát do pdf to tohoto PR)

2020-10-09 08:09 UTC, katkolouchova commented
> 
> 
> Katko, mohla bys prosím v titulcích grafiky nahradit SR za Slovensko? (a nahrát do pdf to tohoto PR)

Jasně, samotné mi SR úplně nesedělo :) Nicméně titulek _Emise skleníkových plynů Slovenska podle sektorků detailně_ se na jeden řádek nevejde. Napadá mě odstranit _detailně_, akorát to pak nebude nebude konzistentní s pojmenováním českých verzí. Pokud ale pro Slovensko publikujeme pouze detailní verzi, nevidím v tom zásadní problém (možná jenom v případě, kdy někdo bude obě grafiky držet vedle sebe).

2020-10-09 08:16 UTC, jankrcal commented
Ano, vynechal bych "detailně". Ta nekonzistence mi přijde drobný problém.

2020-10-09 08:45 UTC, katkolouchova commented
@jankrcal Hotovo.

2020-10-12 05:45 UTC, jankrcal commented
@mukrop, pokud na to nemáš čas, dej prosím vědět, požádám o review někoho jiného.
Ocením i když ten text jen v rychlosti proletíš a upozorníš na věci, které Ti ze svého slovenského know-how nesedí.

2020-10-12 06:17 UTC, mukrop commented
Ah, prepac, neuvedomil som si, ze to caka na mna (myslel som, ze na teba
alebo na Katku).
Mrknem na to dnes.

2020-10-12 07:56 UTC, mukrop commented
Presiel som, text sa mi zda dobry. Trochu som zvazoval, ci ma nerusia tie poznamky, co by sa s tym dalo urobit pri niektorych (nahodne vybranych?) kategoriach, ale asi su tam fajn. Par poznamok:
* [ ] Je to drobnost, ale @katkolouchova nedodrzala pravy okraj, takze percento pri mineralnej produkcii je v zobrazeni na webe mierne orezane. Bolo by super to fixnut, ale nevidim to ako zasadne.
* [ ] Tabulka s datami vidim, ze este nie je dokoncena (vstupne archy ma OK, ale ten hlavny este prezentuje cisla CR).
* [ ] Asi by som navrhol zrusit to "detailne" konzistentne vsade, tj. aj z nadpisu na webe a aj zo slugu (teda premenovat subor).

2020-10-12 07:57 UTC, mukrop requested changes
Komentare v prispevku vyssie. Nie je to nutne, ale chcel by som aspon vyjadrenie, co z toho sa ti zda rozumne zapracovat a co nie.

2020-10-12 09:24 UTC, katkolouchova commented
Text v grafice zkusím trochu posunout, zvládnu to během dne :) Pokud se rozhodneme odstranit detailně, odstranim ho i ze slugu v grafice. Jen mě teda napadá, zda z webu nestáhnout i český nedetailní koláč a u toho, co je teď detailní, zrušit detailní.

2020-10-12 09:39 UTC, ondraspribyla commented
... můj názor: český nedetailni stáhnout, zkrátit slug a az budeme řešit
zobrazování různých verzí grafiky (třeba ze starších let) tak tam mezi
verze přidáme i ten nedetailni...

Dne po 12. 10. 2020 11:25 uživatel katkolouchova <notifications@github.com>
napsal:

> Text v grafice zkusím trochu posunout, zvládnu to během dne :) Pokud se
> rozhodneme odstranit detailně, odstranim ho i ze slugu v grafice. Jen mě
> teda napadá, zda z webu nestáhnout i český nedetailní koláč a u toho, co je
> teď detailní, zrušit detailní.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/666#issuecomment-706999361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EHI3LBIAU4U55JNPNDSKLDPNANCNFSM4SJI3YYA>
> .
>

2020-10-12 10:15 UTC, mukrop commented
V dlhodobom horizonte suhlas s Ondrasom, ale v tomto PR poriesme len
Slovensko, to stahovanie ceskeho a zmeny slugov tam poriesime inde.

>

2020-10-12 14:23 UTC, katkolouchova commented
Grafika upravena, detailně odstraněno.
@jankrcal Změnila jsem v grafice kategorii _Minerální produkce (cement, vápno atd.)_ na _Výroba cementu a jiných minerálů_, aby se to tam lépe vešlo. Je to konzistentní i s tím, co je v textu.

2020-10-14 18:16 UTC, jankrcal commented
Díky za objevení chyby v datasetu, tam byl jen problém s tím, že nebyly aktualizované ty grafy v tabulce, jinak data byla kompletní.

Můžeš prosím udělat merge?

2020-10-14 18:34 UTC, mukrop approved these changes

2020-10-14 18:35 UTC, merged