První verze stránky o atlasu klimatické změny
faktaoklimatu/web pull request #688
Opened 2020-11-10 12:28 UTC by tomas-psorn

- Stránka o atlasu v atlas.md (O. Přibyla, O. Pechník, T. Pšorn)
- Dočasný obrázek atlasu atlas-mockup.png
- Stránka s atlasem přidána do menu
- Odkazy na hlavní straně vedou na stránku s atlasem, ne na pdf

2020-11-10 16:18 UTC, mukrop requested changes
Vyzera to sympaticky :-).
* Ten bocny panel by som dal este o perex vyssie (tj. aby zacinal hned pod nadpisom).
* Tlaciko na stiahnutie by som popisal vystiznejsie – mozno "Stahnout atlas"?
* Sekcia Podporte nas urcite nad sekciu o tlacenom atlase. Navyse asi preformulovat. Bavili sme sa s Ondrasom, ze u nas bude primarne napisane, ze nas maju podporit a potom im posleme atlas a preklik na Lipku bude asi menej vyrazny (dal by som outline tlacitko). To posielanie este nie je vyriesene, takze docasne to asi moze byt aj priamy link na Lipku.
* Licencia pozor! Myslim si, ze Atlas nie je pod licenciou CC! To si treba overit s Lipkou, ale kedze sadzba je ich praca (platena), museli by sa oni explicitne vyjadrit, ze je to CC. K tomu sa musi vyjadrit @ondraspribyla.
* Obrazok je sice pekny, ale nevypoveda nic o tom, co v tom atlase vlastne je. Navrhujem pridat dalsi obrazok pod sekciu "Pouzioti ve vyuce", ktory bude na sirku a vznikne zlepenim screenshotov nejakej vybranej strany (alebo dokonca by tam mohli byt az dve ukazky takychto stran).
* V linke argumentov by som asi nechal boldom "hlavnu myslienku" na samostnatnom riadku a zvysny text zalomil az pod to. A formuloval hlavnu myslienku ako samostatnu vetu s bodkou a potom zacal velkym pismenom. (A ak by si sa rozhodol nehcat to takto, tak pouzivat pomlcky namiesto spojovnikov :-P.)
* Chybaju bibliograficke informacie. Bud vpravo do panelu alebo dole veci ako oficialny nazov, autorov, ISBN, ...
* Nechceme zvyraznit v texte velke mena, ktore nam robili recenziu?
* Odkazy v pravom paneli – vo vseobecnosti na tlacitka nedavame nazvy domen a drzime rovnaky styl. Takze napriklad tlacitko na darovanie by som uprednostnil s textom "Podporte nas" a so srdieckom ako ikonou (tak, ako je na titulke),

2020-11-10 16:19 UTC, mukrop reviewed
A este, divajuc sa do kodu: Pri vacsich textovych pasazach by mohlo byt prehladnejsie prejst do Markdownu. Parent element potom ma tusim `markdown="1"` (pozri sa v zdrojakoch titulky), ale textove pasaze potom vyzeraju ako v ostatnych strankach formatovane cez MD.

2020-11-10 16:24 UTC, ondraspribyla commented
Za sebe dodávám, že moje pozornost je teď potřeba jinde (GRANT + scénáře)
takže dotažení nechávám na vás.
A díky moc za celou tu práci!

O.

On Tue, 10 Nov 2020 at 17:19, Martin Ukrop <notifications@github.com> wrote:

> *@mukrop* commented on this pull request.
>
> A este, divajuc sa do kodu: Pri vacsich textovych pasazach by mohlo byt
> prehladnejsie prejst do Markdownu. Parent element potom ma tusim
> markdown="1" (pozri sa v zdrojakoch titulky), ale textove pasaze potom
> vyzeraju ako v ostatnych strankach formatovane cez MD.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/688#pullrequestreview-527373848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EEDGN4UZXFU7NP2D3DSPFR2HANCNFSM4TQTFGEQ>
> .
>

2020-11-15 17:36 UTC, tomas-psorn commented
Zapracoval jsem zpětnou vazbu. Na formátování se ještě podívám. Přidal jsem rozbalovací sekce s bibliografickými údaji, poděkováním, rezenzenty a krátkou sekci o aktualizaci a dalších dílech.

Kvůli licenci jsem psal email paní Kopáčové, ale ještě mi neodpověděla. @ondraspribyla  říká, že oni se v těch licencích moc neorientují a neřeší to. Dohli jsme se tak, že jí v dalším emailu nabídnu, že bysme to vydávali pod licencí CC a vysvětlím, co to implikuje.

Fotky dodá @ondraspribyla.

2020-12-05 19:55 UTC, tomas-psorn commented
Doplnil jsem licenci a novou fotku.

2020-12-06 14:21 UTC, mukrop approved these changes
@tomas-psorn, este som to trochu preskladal kvoli lepsiemu vizualu. Tiez som si dovolil prerobit fotku na nieco dynamickejsie :-).

Z technickych drobnosti:
* Prosim necommitovat do gitu velke subory (ta nezmensena Anezkina fotka mala asi 3.5MB).
* Prosim nepouzivat inline styly v HTML (bootstrap ma na to casko skratky cez triedy, takze si vystacis aj bez zasahu do CSS).

To nie je kritika, na to som tu ja a review, ze taketo veci odladim :-).

Prosim pozri sa na to, co si myslis o poprehadzovani. Mozme pripade este preskladat, ak chces.

Zaroven by som chcel, aby sa niekto pozrel na texty obsahovo (tomu som sa ja velmi nevenoval). @ondraspribyla?

2020-12-06 19:33 UTC, ondraspribyla approved these changes
Já jsem s textem i výslednou podobou spokojen. Lepší fotku dáme časem, metodiky taky brzo přidáme...

2020-12-07 12:58 UTC, merged