Teplotni anomalie - upgrade textu
faktaoklimatu/web pull request #717
Opened 2021-01-01 23:06 UTC by ondraspribyla

Předělal jsem text k grafu Teplotní Anomálie. Výsledek částečně integruje text z atlasu, vysvětluje počet stanic (viz #435), jasněji odkazuje souvislosti... Pull request může v principu počkat na update sady o rok 2020 (který očekáváme koncem ledna)
ale raději bych ho zkompletoval už teď, dá mi to pocit, že se věci hýbou :-). V tomto PR, nebo  při updatu by stálo za to vyřešit: 

- [ ] SLUG - tento graf by měl mít název teplotni-anomalie, nikoliv vyvoj-teplotni-anomalie
- [ ] odkazování na související grafiky pomocí náhledů grafů, které by byly vhodně vloženy v textu 

O textové review prosím @jankrcal, @crysman, nebo @mgrabovsky - kteří možná ocení text upgradu, o technické review prosím @mgrabovsky  nebo @mukrop .

2021-01-02 01:17 UTC, crysman requested changes
narazil jsem na chybku, možná jich bude víc, projdu to a commitnu fix

2021-01-02 01:55 UTC, crysman commented
OK, @ondraspribyla za mě vyřešeno PR#718 https://github.com/faktaoklimatu/web/pull/718/files?diff=split&w=1

2021-01-02 01:56 UTC, crysman commented
@ondraspribyla nějak jsem se ponořil jen do hard-data, teď trochu meta - ano, jsem nyní s textem spokojen po Tvé úpravě, dobrá práce! ;)

2021-01-02 16:19 UTC, mukrop commented
Slug som pridal do issue ako #719, nahlady budu po zaintegrovani vetvy s prestrukturovanim textov.

2021-01-02 16:28 UTC, mukrop approved these changes

2021-01-02 16:58 UTC, crysman commented
@mukrop čau Martin, jen pro vyjasnění:

1. typografii (pomlčky, spojovníky) jsem neřešil, lebo je na to přece automat post-processingový, ne?
2. dle title Tvého commitu jsem přehlédl nějaké markdown syntax errory :( - jaké? Máme nějaký osvědčený MarkDown validátor? Že bych to při svých korekturách prohnal i tím dycky...
3. Zatím nemůžu pohodlně vyvíjet lokálně, lebo pořád ještě vázne ten docker :/ (viz [zde](https://github.com/faktaoklimatu/web/issues/638))

díkec

2021-01-02 21:04 UTC, merged

2021-01-03 12:17 UTC, mukrop commented
> 1. typografii (pomlčky, spojovníky) jsem neřešil, lebo je na to přece automat post-processingový, ne?

Na pomlcky to nie je – a ani nemoze byt, pretoze niekazdy spojovnik ma byt pomlcka (dokonca plati nezavisle na tom, ci su okolo neho medzery alebo nie). Realne to nejde rozumne automatizovat.

> 2. dle title Tvého commitu jsem přehlédl nějaké markdown syntax errory :( - jaké? Máme nějaký osvědčený MarkDown validátor? Že bych to při svých korekturách prohnal i tím dycky...

Nic extra zasadne. Ja mam v MS Code pridany [MD linter](https://github.com/DavidAnson/vscode-markdownlint) a zvyknem to pri kontrole docistit. Nadbytocne prazdne riadky na konci suboru, medzery na konci riadku a pod. Nad ramec toho sa snazim, aby jeden odstavec textu bol na jednom riadku kvolu prijemnemu zalamovaniu v editoroch (byva to inak, ked ludia kopiruju text od niekial, kde bolo ine zalamovanie, napr. z atlasu).

> 3. Zatím nemůžu pohodlně vyvíjet lokálně, lebo pořád ještě vázne ten docker :/ (viz [zde](https://github.com/faktaoklimatu/web/issues/638))

Nie som 100% presvedceny, ze Docker bude najpohodlnejsi. Ja som si urobil druhu vyvojovu stanicu na Windows, takze budem robit drobne zmeny v repe, aby to malo poholdny build aj na Windowse. Mozno to aj tebe ulahci local build.

2021-01-05 23:33 UTC, crysman commented
@mukrop ad 1: juj, my fault, hlavně že jsem to sám napsal v našich [internal guideliness](https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA/edit#heading=h.r9yi1in5bqht), lol, lame, pardon - prostě jak z toho člověk vypadne na delší dobu z těch edit prací, tak zmizí spousta nacashovaných věcí z hlavy...
ad 2: OK, dík za tip, nicméně, to pro mě použitelné nebude, nemám Wokna ani Wine. Základní "validaci" dělá preview samo o sobě, když člověk edituje tady na GitH, ale při local buildu to chybí... Vím, že jsem kdysi používal toto při lokálním vývoji - https://dillinger.io/ - to pěkně nasimuluje to "preview". Tak uvidíme, třeba něco objevíme časem.
ad 3: zatím to vypadá, že si budu muset vystačit s legacy variantou - prostě všechny dependence mít přímo v OS bez virtualizace... Jen mě na tom zaráží, že jsem sám, co to řeším - to jako mají všichni Fedoru (?)

2021-01-09 15:46 UTC, jankrcal commented
Drobné komentáře ex post:
 - VSCode funguje (snad) i na linuxu. Pěkný IDE, můžu doporučit. https://code.visualstudio.com/docs/setup/linux
 - Mně docker taky nefunguje (pracovní systém založená na debianu).